# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cv',
            new_name='uv',
        ),
    ]
