# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191207_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=True, verbose_name='markdown 语法'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='正文可以为 markdown', verbose_name='正文'),
        ),
    ]
